import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

import Messages from '../components/Messages';
import { UserInputs } from '../components/UserInputs';

import {CreateRoomForm} from '../components/CreateRoomForm';

import {Rooms} from '../components/Rooms';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Chat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <Rooms />
        <CreateRoomForm />

      </div>
)
}

export default Home
