import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

import axios from 'axios';

import {API_URL} from '../shared/utils';

const Home: NextPage = () => {
  async function handleClick(e: MouseEvent<HTMLButtonElement>) {
      console.log('clicked');
      console.log(API_URL);
      const data = (await axios.post(API_URL + "/hello", {data: "test"})).data;
      console.log(data);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        Index page

        <button onClick={handleClick}>Click me</button>

      </div>
)
}

export default Home
